version: '3.4'

services:
  nginx: 
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      # - static_volume:/app/backend/server/django_static
      - ./nginx/production:/etc/nginx/conf.d
    env_file:
      - ./codehere_front/.env
    depends_on:
      - backend
  backend:
    image: codehere_back
    build:
      context: ./codehere_back
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - back_migrations
    restart: always
  back_migrations:
    image: codehere_back
    build:
      context: ./codehere_back
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "python manage.py migrate"]
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12
    container_name: codehere_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
 
volumes:
  postgres_data: