# Generated by Django 5.0 on 2024-01-01 19:41

from django.db import migrations


def create_data(apps, schema_editor):
    MapObject = apps.get_model('map_objects', 'MapObject')
    MapObject(username="clevershovel", code="print('Hello, world')").save()
            

class Migration(migrations.Migration):

    dependencies = [
        ('map_objects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
