# Generated by Django 5.0 on 2024-01-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_objects', '0002_map_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapobject',
            name='lat',
            field=models.FloatField(db_default=models.Value(0.0), verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='mapobject',
            name='lon',
            field=models.FloatField(db_default=models.Value(0.0), verbose_name='Longitude'),
        ),
    ]
